services:
    root:
      image: node:22
      working_dir: /app
      volumes:
        - ./:/app
      tty: true

    demo:
      image: node:22
      working_dir: /demo
      depends_on: 
        - root
      tty: true
      volumes:
        - ./demo:/demo
        - ./tsconfig.json:/tsconfig.json:ro

    library:
      image: node:22
      working_dir: /library
      depends_on: 
        - demo
      tty: true
      volumes:
        - ./library:/library
        - ./tsconfig.json:/tsconfig.json:ro
